version: '3'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.frontend.rule=Host:traefik.julien.tech"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=https"
      - "traefik.docker.network=web"
      - "traefik.port=80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme.json:/etc/traefik/acme.json
    
networks:
  web:
    external: true