

debug = false
logLevel = "WARNING"


[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "julien.tech"
  watch = true
  exposedbydefault = false

defaultEntryPoints = [ "https"]

# Entrypoints, http and https
[entryPoints]

# http should not be redirected to https
[entryPoints.http]
  address = ":80"

# https is the default
[entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[entryPoints.admin]
  address = ":8081"

[rest]
 entryPoint = "ping"

[ping]
  entryPoint = "ping"

[api]
  entryPoint = "admin"
  dashboard = true
  [web.statistics]


  [file]
    [backends]
     [backends.backend1]
       [backends.backend1.servers.server1]
        url = "http://127.0.0.1:8081"

[acme]
 email = "admin@julien.tech"
 storage = "/etc/traefik/acme.json"
 onHostRule = true
 entryPoint = "https"

    
 [acme.httpChallenge]
  entryPoint = "http"